### ISSUE TITLE
Adding documentation on how to run it in 2023

### ISSUE THREAD

**Issue by matanbaruch** [netanelkoli/LionKingAssembly#1]
Hey,
Can you please add documentation on how to run it?
Do I need a specific processor?

**Comment by matanbaruch** [comment]
@netanelkoli

**Comment by netanelkoli** [comment]
resolved. @matanbaruch - check documentation

**Comment by matanbaruch** [comment]
Works!
Thanks

<img width="637" alt="image" src="https://user-images.githubusercontent.com/36934912/226189869-5b7feccc-25f9-4e07-93d1-6af238b39d4a.png">

<img width="636" alt="image" src="https://user-images.githubusercontent.com/36934912/226189893-db738105-ec66-428d-bfc8-780ef79c2668.png">
